# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cellulove
brand: Cellulove
author: Dalia Yousef
email: daliayousef7@gmail.com
copyright: cellulove.me
description: >- # this means to ignore newlines until "baseurl:"
  Cellulove is a blog demonstrating the similarities between human cells and tissues
  and everything surrounding us. Content of this website is authored by Doctor
  Dalia Yousef, assistant lecturer of histology and cell biology at Ain Shams University
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cellulove.me" # the base hostname & protocol for your site, e.g. http://example.com

# SEO
social:
  name: Dalia Yousef
  links:
    - https://github.com/kimfucious
    - https://www.linkedin.com/in/kimaford/
webmaster_verifications:
  google: uubLfpcORmDWkM8pI-yKODVVZD3VSpUYFSwkQJcOuZE

# Social icons
show_social_icons: true
facebook_username: dahlia.matouk
linkedin_username: dalia-yousef-04486949

# Collections
collections:
  posts:
    output: true
    permalink: "/:collection/:title/"

# Defaults : these allow you to set default values for front matter
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post 
      type: post
  - scope:
      path: "pages"
      type: pages
    values:
      layout: default 

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 8 
  paginate_path: "/page:num"
  sort_reverse: true
  title: ":title"
  trail:
    before: 2
    after: 2

# Plugins
plugins: [jekyll-paginate-v2, jemoji, jekyll-sitemap, jekyll-seo-tag, jekyll-feed]

# Build settings
theme: jekyll-theme-dinky

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
